### ISSUE TITLE
ANC Logic - Diagnosis and Next Steps: Miscarriage or Molar Pregnancy [6h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#142] opened 2022-02-07 23:32 UTC
## Issue

When a patient meets the criteria for Miscarriage or Molar Pregnancy it will trigger the pop-up and immediately go to referral. The patient will not finish the encounter as this is an emergency situation. 

Pop Up | Next Steps 
--|--
<img width="265" alt="Screen Shot 2022-02-07 at 6 28 46 PM" src="https://user-images.githubusercontent.com/77505464/152889551-0df4db4b-2c74-4959-b7f0-29f62abf3d99.png"> | <img width="263" alt="Screen Shot 2022-02-07 at 6 29 29 PM" src="https://user-images.githubusercontent.com/77505464/152889598-34ce0cdd-795d-486f-bcf3-b828bc4d7d59.png">

## Supporting Documents 
- The logic for ANC can be found [here](https://docs.google.com/spreadsheets/d/1awAwPTMxRMhb2CSP3ocJvbOJravIaoPb2Q-RERe9KQ8/edit#gid=1762936493) on the ANC - Nurse tab.
- The designs can be found in Figma under [HC - ANC](https://www.figma.com/file/nKKYxDmnEPm7CiXSXO1pq7/E-Heza-2021?node-id=5862%3A38746) under the purple logic heading. 

## Note: 
- In the case that the design in the issue varies from what is in Figma, ping Jeanette on slack and use the Figma design. 
 
## To Do: 

- Create next steps activities 
- Diagnosis Logic 
- Create necessary pop-ups and the logic to display them 
- Style per Design

**Comment by adamhstewart** [comment] 2022-03-29 18:48
## QA Analysis

## Works as designed

- Under 28 weeks, vaginal bleeding, the popup alert is shown and directed to Next Steps


## Needs Followup
- This may not need followup, but currently after the referral, the progress report is shown (as expected), but because there is no "close encounter" button on it, the user needs to back track into the encounter, where you can then close it. If we will be adding the end encounter button (also pointed out in other issues) this can likely be moved over.

**Comment by adamhstewart** [comment] 2022-03-30 14:08
@anvmn @jeanette-pelizzon I am moving this over in favor of followup in #203 .

**Closed as completed** 2022-09-30 07:58 UTC
Labels: ANC - Health Center, Ready for Acceptance, ANC Logic
