### ISSUE TITLE
Patient Record - Begin Encounter - Antenatal [3h]

### ISSUE THREAD

**Issue by jeanette-pelizzon** [TIP-Global-Health/eheza-app#96] opened 2022-01-06 22:18 UTC
## Issue 

You will be able to immediately enter into an antenatal encounter for the selected patient from the patient record in two different ways. 

(1) At the bottom of the overview screen, there is a button that will say "Begin Encounter" and this will take you to a screen where the user can select which type of encounter to begin for the patient. Only the relevant encounter types will populate. (Ex: a standard pediatric visit wouldn't populate for a 40yo) 

(2) At the bottom of each progress report an "Begin Encounter" button will appear with the same flow as above. 

Button Example | Begin Encounter Screen 
--|-- 
<img width="449" alt="Screen Shot 2022-01-06 at 5 18 13 PM" src="https://user-images.githubusercontent.com/77505464/148460272-e1d1d917-2e34-4054-a269-b65a6724c214.png"> | <img width="297" alt="Screen Shot 2022-01-06 at 5 15 09 PM" src="https://user-images.githubusercontent.com/77505464/148459983-bd90df4e-465c-4a24-ac98-190dc987726c.png">

## Tasks 
- update the origin of the report ( reference #103) 
- update button on the bottom "Start Encounter" 
- Link to new start encounter page
- Create start encounter page 
- Ensure those buttons link to the create encounter types

**Comment by isapisa** [comment] 2022-01-07 10:01
duplicate of https://github.com/TIP-Global-Health/eheza-app/issues/76

**Closed as completed by isapisa** 2022-01-07 10:01 UTC
Labels: duplicate, Patient Record
