### ISSUE TITLE
Burundi localization follow ups

### ISSUE THREAD

**Issue by anvmn** [TIP-Global-Health/eheza-app#871] opened 2023-09-13 18:50 UTC
Follows up https://github.com/TIP-Global-Health/eheza-app/issues/798

1. Ubudehe:
   - Resilience kick off survey - ubudehe question for Nurse.
   - Mother Fbf - logic for distribution (ubudehe 1 or 2 receive Fbf, others do not).

2. Wording at `Translate.elm` (specific mentions of Rwanda):

![Selection_2097](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/5dc3509f-bba9-488a-a44f-200bf0d31e56)
![Selection_2098](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/043608e7-eb15-4321-bb04-2ce95404de79)
![Selection_2099](https://github.com/TIP-Global-Health/eheza-app/assets/17882245/c899b9ca-f96f-4e92-a944-380bb7e6fa1e)

**Comment by anvmn** [comment] 2023-09-14 05:15
@adamhstewart please advice how these should be handled.

**Comment by adamhstewart** [comment] 2023-09-14 15:59
### English translations:
- Remove the second sentence of the Rotavirus vaccine to eliminate specific reference to Rwanda
- Change Covid question to remove "in Rwanda"
- Stock supplier values: we need to be able to make the suppliers list configurable by an admin. We will (eventually) also need this for some other functionalities as well (for example, lists of medications, which may be different in different countries. Out of scope for this issue, but in a new issue we should consider:
    - A backend admin section for custom select lists
    - A way to integrate that wire that to the frontend question.

Overall this last issue is not a blocker for creating and releasing multisite capability because these sections will not be used by test audience in Burundi.

**Comment by anvmn** [comment] 2023-09-14 17:10
@adamhstewart 

>  we need to be able to make the suppliers list configurable by an admin. We will (eventually) also need this for some other functionalities as well (for example, lists of medications, which may be different in different countries. Out of scope for this issue, but in a new issue we should consider:
 - A backend admin section for custom select lists
 - A way to integrate that wire that to the frontend question.

Well, supporting such type of configuration at the App seems to me as a pandora box we better not open.
 
Considering suppliers list configurable, we'll need to  resolve several issues, which don't have easy solutions.

Main issue:
 - How do we configure the content type to be able to store these configured values.
 We could take an approach where we define generic options for response (`ans1, ans2, ..., ans10`), and then the configuration that is sent, only specifies the labels for the options (note that these need to be translated to all languages), but then, if configuration changes over time, it will be hard to know what `ansX` was representing at the time it was set.

If we consider making medicine configurable, it's even more problematic, as it's not only medication name, but also all kind of instructions that come with it and shown on form.
So, as I see it, best approach is to expand medication set, and suggest medication based on current site.
Besides, it's very likely that prescription logic will need changing, so there's no way to avoid adding code to support it.

Therefore, I think we should be handling such change requests by developing small releases with needed changes. Don't think it will be required too often.

//cc @amitaibu

**Comment by balagan73** [comment] 2023-11-14 15:03
These were confirmed in QA for https://github.com/TIP-Global-Health/eheza-app/issues/798

**Closed as completed** 2023-11-21 13:37 UTC
Labels: multisite
