### ISSUE TITLE
When there is long urine dipstick test, the results of the test appear twice in the report

### ISSUE THREAD

**Issue by LudmilaGoichman** [TIP-Global-Health/eheza-app#1201] opened 2024-06-06 08:13 UTC
- long urine dipstick test (point of care OR lab)
- correct or not correct results

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/408410f6-27e1-461e-92d0-1a7ea6887dc2">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/882a7522-4b9f-4794-b1d5-f590e02336fb">
---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/046a5f43-d315-4988-a3b3-ad61067fbceb">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/7cd0ec32-a6e8-4dd2-9748-dc39afb84a9b">
---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/edff8389-0b89-4507-aab6-d0a95738c23f">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/e06d334e-969e-4038-b444-5c9f05be0c0c">
---|---

<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/5972a53b-8822-4f67-b69f-c52139305a8c">|<img width="351" alt="image" src="https://github.com/TIP-Global-Health/eheza-app/assets/35059802/1018be0d-a553-4fa3-820f-75d4a5fbdc55">
---|---

**Comment by anvmn** [comment] 2024-06-13 13:23
@LudmilaGoichman This works as designed.

The case we're dealing here is having partial (short) or full (long results).
Since in report we show history, we show 2 versions.
Short shows all results of first 3 indicators (both from short and long).
Longs shows all indicators (first 3 are also, from short and long).

If explanations is satisfactory, please close the issue.

**Closed as completed** 2024-06-17 05:23 UTC
